version: '3.8'
services:

  #PHP Service
  app:
    container_name: todo_list_app
    build:
      context: ./docker
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
            - ./:/var/www
    restart: unless-stopped
    tty: true
    networks:
      - todo_list_network
  #Web Server(NGINX)
  web:
    container_name: todo_list_web
    build:
        context: ./docker
        dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
        - ./:/var/www
    ports:
        - 8081:80
    networks:
      - todo_list_network

  #MySQL Service
  db:
    container_name: todo_list_db
    image: mariadb
    restart: unless-stopped
    tty: true
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql/
      # - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - todo_list_network

  phpmyadmin:
    container_name: todo_list_pma
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=todo_list_db
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD}
      - MAX_EXECUTION_TIME=3600
      - UPLOAD_LIMIT=512M
    networks:
      - todo_list_network
networks:
  todo_list_network:
    driver: bridge
